### ISSUE TITLE
Добавить пример параллельной имплементации фильтра

### ISSUE THREAD

**Issue by Daniil-Osokin** [itlab-vision/itlab-vision#50]
@druzhkov-paul @valentina-kustikova Собираюсь добавить пример параллельной имплементации какого-нибудь фильтра (как только в master что-нибудь попадет). Это будет полезно?

**Comment by valentina-kustikova** [comment]
Да, конечно. Код из всех pull request должен оказаться в общем репозитории не позднее четверга. Можно будет взять любой из фильтров. Мы для демонстрации чего-либо используем фильтр сепии, но он написан на базе функций OpenCV.

**Comment by kirill-korniakov** [comment]
Даниил, сепия вполне подходит. Там есть вызов `cvtColor` в одну строчку. Так вот если можно распараллелить его, то это уже помогло бы в ряде фильтров, поскольку в конверсии цветов часто есть тормоза, см. https://docs.google.com/spreadsheets/d/1jX-Oqm9ATS579NxDH6X6GUVdGGAh9r2cOoy9ACqapDQ/edit#gid=0

**Comment by Daniil-Osokin** [comment]
Сепию смотрел, cvtColor'ы почти все многопоточные в OpenCV (вызов `HSV2BGR` конверсии: https://github.com/Itseez/opencv/blob/2.4/modules/imgproc/src/color.cpp#L4095, имплементация `cvtColorLoop`: https://github.com/Itseez/opencv/blob/2.4/modules/imgproc/src/color.cpp#L195). В 3.0 уже всё с OpenCL. Тут уже всё относительно хорошо. Может сборка OpenCV без поддержки многопоточности?

**Comment by valentina-kustikova** [comment]
Сборка по умолчанию точно без поддержки многопоточности, поэтому я и предложила взять один из тех фильтров, которые зальют ребятами первым. Там почти везде есть явные циклы обхода по пикселям изображения.

**Comment by Daniil-Osokin** [comment]
Ок. Я хотел OpenCV'шный `parallel_for _` использовать, но если OpenCV без многопоточности, то надо что-нибудь другое. Есть предпочтения по технологиям (наверное TBB)?

**Comment by valentina-kustikova** [comment]
Это только сейчас не подключена многопоточность. Как только ребята начнут заниматься распараллеливанием, все будет. Поэтому мы хотели видеть распараллеливание именно через `parallel_for_` из OpenCV.

**Comment by Daniil-Osokin** [comment]
Хорошо.

**Comment by valentina-kustikova** [comment]
Даниил, в репозитории появились реализации двух фильтров. Думаю, можно выбрать попроще  и решить задачу с распараллеливанием.

**Comment by Daniil-Osokin** [comment]
Ок, займусь.
