### ISSUE TITLE
Regression test for tint filter

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/itlab-vision#60]
Добавить регрессионный тест для фильтра `tint`.

**Comment by valentina-kustikova** [comment]
@KruchDmitriy просьба, оперативно добавить регрессионный тест по вашему фильтру.

**Comment by KruchDmitriy** [comment]
Добрый день,

К сожалению у меня последние дни не было интернета, и ваше сообщение я
заметил только сегодня.
Я добавил регрессионный тест.

23 апреля 2014 г., 13:21 пользователь Valentina
notifications@github.comнаписал:
